version: "3.7"
services:
  # Контейнер базы данных
  db:
    container_name: db_name
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  # Контейнер для redis
  redis:
    image: redis:7
    container_name: redis_app

  # Контейнер с приложением
  app:
    build:
      context: .
    env_file:
      - .env
    command: ["/bewise/app.sh"]
    ports:
      - 8000:80
    depends_on:
      - db
      - redis

volumes:
  postgres_data: